// <auto-generated />
using System;
using ClubManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605023123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("VenueId");

                    b.HasIndex("SlotId", "BookingDate", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Member");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@clubapi.com",
                            FullName = "Admin",
                            PasswordHash = "$2a$11$CHCM8EZho/FJGRE8I4oKv.xEAyIUKKy4gzCYCAUwR/xvHy5qbPCyS",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Large multi-purpose hall",
                            IsActive = true,
                            Name = "Main Hall"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Outdoor clay court",
                            IsActive = true,
                            Name = "Tennis Court"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Olympic-size pool",
                            IsActive = true,
                            Name = "Swimming Pool"
                        });
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.VenueSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = "Monday",
                            EndTime = new TimeOnly(10, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0),
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = "Monday",
                            EndTime = new TimeOnly(12, 0, 0),
                            StartTime = new TimeOnly(10, 0, 0),
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = "Tuesday",
                            EndTime = new TimeOnly(9, 0, 0),
                            StartTime = new TimeOnly(7, 0, 0),
                            VenueId = 2
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = "Thursday",
                            EndTime = new TimeOnly(9, 0, 0),
                            StartTime = new TimeOnly(7, 0, 0),
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = "Wednesday",
                            EndTime = new TimeOnly(8, 0, 0),
                            StartTime = new TimeOnly(6, 0, 0),
                            VenueId = 3
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = "Friday",
                            EndTime = new TimeOnly(8, 0, 0),
                            StartTime = new TimeOnly(6, 0, 0),
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Booking", b =>
                {
                    b.HasOne("ClubManagementApi.Models.Entities.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubManagementApi.Models.Entities.VenueSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubManagementApi.Models.Entities.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Slot");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.VenueSlot", b =>
                {
                    b.HasOne("ClubManagementApi.Models.Entities.Venue", "Venue")
                        .WithMany("Slots")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Member", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.Venue", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("ClubManagementApi.Models.Entities.VenueSlot", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
